### ISSUE TITLE
Plugin not working after updating PyMOL

### ISSUE THREAD

**Issue by mirabel-s** [vanderkamp/enlighten2-pymol#1]
Hello,

The Enlighten2 plugin was working for me until I updated brew and PyMOL. I can still install it, but once I select it in the plugin menu I get this error:

arguments did not match any overloaded call:
  move(self, a0: QPoint): argument 1 has unexpected type 'float'
  move(self, ax: int, ay: int): argument 1 has unexpected type 'float'

I got this error on 2 different computers (Intel and M2).

Thank you.

**Comment by kzinovjev** [comment]
Hi @mirabel-s! I just merged the fix mentioned above, it should solve the issue.

**Comment by mirabel-s** [comment]
@kzinovjev Thank you so so much!!! It works now:)
