### ISSUE TITLE
Issue with minimizing h in sphere during PREP

### ISSUE THREAD

**Issue by mirabel-s** [vanderkamp/enlighten2-pymol#3]
Hello,

I keep running into the same issue while running the PREP protocol. I am following the tutorial steps, and I wonder if this is an issue due to the Python updates, as I was able to run simulations previously. I get an error message at the minimize_h_in_sphere step (image attached) and I also included an image of the log file. 

Thank you!
<img width="586" alt="Screenshot 2023-08-03 at 10 54 57 PM" src="https://github.com/vanderkamp/enlighten2-pymol/assets/140772125/89baed5d-15b1-4085-bf28-438fed3b48a8">
<img width="457" alt="Screenshot 2023-08-03 at 10 55 07 PM" src="https://github.com/vanderkamp/enlighten2-pymol/assets/140772125/0170cf1f-5f42-480d-84a3-735b43a8d62f">

**Comment by marcvanderkamp** [comment]
Hello Mirabel,

The issue in this case is the atom name you are using as the centre of the
water sphere:
O5’

If you change it to a name without a (single) quote at the end, all should
work as normal.
(Ideally use a name that is unique in your ligand.)

Best wishes,
Marc

**Comment by mirabel-s** [comment]
Hi Dr. Van der Kamp,

It’s working great now, thank you so much!

Best,

Mirabel
